### ISSUE TITLE
Unicode characters don't display correctly

### ISSUE THREAD

**Issue by rmgui** [MBach/LeMondeRssReader#10]
## Issue
In the following categories, the unicode characters do not display correctly on the preview page:
* International
* Economie
* Culture
* Idées
* Sports
* Sciences
* Pixels
* Campus
* Les décodeurs
* Vidéos
This issue does occur with both themes.

## About my device
Model: Xiaomi Redmi Note 5
Android version: 7.1.2 (MIUI Global 9.2)
App version: 1.2

## Screenshots
The copyright for the content displayed may belong to lemonde.fr.
On this page, the unicode characters display correctly.
![À la une - displaying correctly](https://user-images.githubusercontent.com/32839666/42124851-bbd62fd6-7c6a-11e8-9099-dea11b10e898.png)
And here they don't.
![Société](https://user-images.githubusercontent.com/32839666/42124852-bbfbe99c-7c6a-11e8-88f4-b8f819bf70f0.png)
Neither here.
![Vidéos](https://user-images.githubusercontent.com/32839666/42124853-bc1c3f44-7c6a-11e8-9cd3-6b1ea105fe01.png)

**Comment by rmgui** [comment]
The unicode characters display correctly now. Thanks!

**Fixed**

**Comment by MBach** [comment]
@rmgui actually I've tried a very strange fix, because the feed from lemonde.fr isn't really well formed. It seems to work, but I'm note 100% sure why ...

**Comment by MBach** [comment]
In `RssService.java`:
```java
    private final Response.Listener<String> onFeedReceived = new Response.Listener<String>() {
        @Override
        public void onResponse(String response) {
            try {
                ArrayList<RssItem> rssItems = parser.parse(new String(response.getBytes("UTF-8")));
                Intent result = new Intent();
                result.putParcelableArrayListExtra(PARCELABLE_EXTRAS, rssItems);
                reply.send(RssService.this, FETCH_SUCCESS, result);
            } catch (@NonNull PendingIntent.CanceledException | UnsupportedEncodingException e) {
                Log.e(TAG, "onHandleIntent error", e);
            }
        }
    };
```

In `RssParser.java`:
```java
    ArrayList<RssItem> parse(@NonNull String stream) {
        ArrayList<RssItem> items = null;
        try {
            XmlPullParser parser = Xml.newPullParser();
            parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false);
            InputStream s = new ByteArrayInputStream(stream.getBytes("ISO-8859-1"));
            parser.setInput(s, "UTF-8");
            parser.nextTag();
            parser.require(XmlPullParser.START_TAG, null, TAG_RSS);
            items = readFeed(parser);
        } catch (@NonNull XmlPullParserException | IOException e) {
            Log.w(e.getMessage(), e);
        } finally {
            if (items == null) {
                items = new ArrayList<>();
            }
        }
        return items;
    }
```
