### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by klauf** [MBach/LeMondeRssReader#11]
Salut MBach

The app was working great, however since a few days only the article list is loading, as soon as you choose an article there is no text, only the picture on the top. Aware of the issue? Other people concerned?
best

**Comment by MBach** [comment]
Hello @klauf 
I'm aware of this! It's very simple, LeMonde.fr has a new website, and I'm parsing the DOM to render articles inside the App. So I have to rewrite a lot of rules in order to scrap text.

**Comment by klauf** [comment]
I thought it was something like this! Simple but painful. Well, thanks.

**Comment by ptibubu** [comment]
The sources of a v1.15 which seem to fix the dom parsing have been commited. Any chance to see it released?
Thank for your app !

**Comment by MBach** [comment]
Main articles are loading again. I still need to parse blogs and other special articles, like live events etc.
