### ISSUE TITLE
Crash on some Articles.

### ISSUE THREAD

**Issue by ghost** [MBach/LeMondeRssReader#13]
The app seems to crash on some articles.
The articles seems random but it happens always on the sames and at the same place on an article.
Seems like some rendering issue.

**Comment by MBach** [comment]
Hi @Drhaal 
Yep, I know... I need to fix this. My parser is doing some weird things this they changed completely the DOM. I wish they could send some JSON (the did once, but it was a mistake from their side, damn it!)

**Comment by ghost** [comment]
Well hope you will be able to solve this, good luck.
And thanks for the app.

**Comment by damiengo** [comment]
I think MR #17 closes this issue.
