### ISSUE TITLE
I can't log in

### ISSUE THREAD

**Issue by paour** [MBach/LeMondeRssReader#2]
When I try to authenticate to my Le Monde subscriber account, I get a not implemented message at the bottom of the screen.

**Comment by MBach** [comment]
That's right.

It's not implemented, and in fact, I'm not sure if I can bypass secure login...

**Comment by ilesinge** [comment]
Hi, I tried to login too, and was a bit confused by the "not implemented" message. Maybe you should remove the "login" placeholder altogether?
Anyway, found this app on fdroid today, and I already ditched the official Le Monde app, because this one is way better! Thanks :)

**Comment by irwinbruneau** [comment]
Hi, if it's possible i really want to login that's would be great thank you for this app by the way

**Comment by MBach** [comment]
Won't be implemented
