### ISSUE TITLE
hope Support TTS (Text-to-Speech) function

### ISSUE THREAD

**Issue by 11fen** [MBach/LeMondeRssReader#22]
hope
Support TTS (Text-to-Speech) function

**Comment by MBach** [comment]
Hi @11fen 

I have activated TTS system-wide on my Galaxy S10e and everything seems to be working:

![Screenshot_20191228-140834_LeMonde](https://user-images.githubusercontent.com/1532657/71544163-d802cd80-297b-11ea-9cf4-555228f8bd54.jpg)

When I click on an item, I have a blue rectangle and the article is being read by TTS function. What exactly do you expect by TTS function?

**Comment by MBach** [comment]
@11fen ?
