### ISSUE TITLE
No comments on premium articles

### ISSUE THREAD

**Issue by Achi-Tect** [MBach/LeMondeRssReader#30]
Hello,
I don't have a paid LeMonde account so I understand that I can't have full access on premium articles.
But I think the comments should be visible even on premium articles.
For example, this is a premium article : https://www.lemonde.fr/planete/article/2020/06/03/les-contraintes-liees-au-covid-19-continuent-a-peser-sur-les-hopitaux_6041566_3244.html 
The comments are accessible if we add "?contributions" : https://www.lemonde.fr/planete/article/2020/06/03/les-contraintes-liees-au-covid-19-continuent-a-peser-sur-les-hopitaux_6041566_3244.html?contributions
I would be great if these comments were displayed.

**Comment by MBach** [comment]
I've started to do this when I've rewritten the App in React-Native, but I've noticed a few bugs on some paid articles. Therefore, I've removed this possibility. 

I don't remember exactly what was the issue, a 404 or some missing node in the DOM.

But I can review a Pull Request (because right now I don't have much time to code on this project).

**Comment by MBach** [comment]
Hello @Achi-Tect 
You can test it, the functionnality was hidden on purpose. I have reverted the changes.
Let me know if it's not working on some paid articles

**Comment by Achi-Tect** [comment]
Thank you very much @MBach ! 
It works even better than before with the addition of the "comments" button at the bottom.

However it breaks the "go back" arrow at the top left because it no longer leads to the articles list but back to the comments if you opened them. Was it the reason why you had that functionality hidden ?

**Comment by MBach** [comment]
Good catch on the Go Back, I usually use the physical back button from my phone. I'll force the route to Home instead.

At first, the functionality was hidden to mimic the behavior on the website.
