### ISSUE TITLE
no More articles

### ISSUE THREAD

**Issue by plegrand1** [MBach/LeMondeRssReader#33]
The latest Version only display logo and no text. 
Thanks

**Comment by MBach** [comment]
Yep. I've seen that also a few days ago

**Comment by plegrand1** [comment]
1.21 Version works Fine. Not the 2.1.3.


Le 12 octobre 2020 21:12:51 GMT+02:00, Matthieu BACHELIER <notifications@github.com> a écrit :

**Comment by MBach** [comment]
@plegrand1 I've published the 2.1.4 a few minutes ago. You need to wait an update from f-droid, or you can build the App by yourself from the source.
