### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [MBach/LeMondeRssReader#34]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box is half blocked. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103165857-dbaf8580-4857-11eb-9e22-120ae1901389.png)
App version is 2.1.4, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="475" alt="bug-lemonde" src="https://user-images.githubusercontent.com/18572115/103194707-758c3680-491b-11eb-8197-806c44cc4bc2.png">

**Comment by MBach** [comment]
Hello,
OK I see your problem about font size. In fact, each block has a fixed sized, because it was simpler for me to put the image. I will make some changes in case font size is set to the max.
Regards,

**Comment by MBach** [comment]
I can reproduce this issue when I set font size to the max:

![Screenshot_1609189983](https://user-images.githubusercontent.com/1532657/103243358-ea7e6100-4959-11eb-9e89-b5c42b7ac004.png)

**Comment by MBach** [comment]
**Font scaling 100%:**
![Screenshot_20201229-000135_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248029-51efdd00-4969-11eb-801d-29e4a7b7b770.jpg)

**Font scaling 110%:**
![Screenshot_20201229-000116_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248028-51574680-4969-11eb-9bbb-8f7a264d0b6d.jpg)

**Font scaling 130%:**
![Screenshot_20201229-000104_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248027-51574680-4969-11eb-9add-5375e7954cea.jpg)

**Font scaling 150%:**
![Screenshot_20201229-000050_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248026-50beb000-4969-11eb-9b95-fdec23508929.jpg)

**Font scaling 170%:**
![Screenshot_20201229-000027_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248023-50261980-4969-11eb-9b41-50693a6dcb51.jpg)

**Font scaling 200%:**
![Screenshot_20201229-000007_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/103248030-51efdd00-4969-11eb-83b4-65d8c02d6660.jpg)
