### ISSUE TITLE
App has non-FOSS deps

### ISSUE THREAD

**Issue by licaon-kter** [MBach/LeMondeRssReader#35]
...as `react-native-device-info` <8.0.0 depends on GMS

I'm preparing a PR based on https://github.com/jitsi/jitsi-meet/issues/8353

**Comment by licaon-kter** [comment]
Could we get a minor version bump so F-Droid updates?

**Comment by MBach** [comment]
Yeah. I could. But nope. With latest dependencies, there's a small glitch quite annoying when opening an article. The screens goes from black to white when transition is happening, then black again and the article is visible.

**Comment by licaon-kter** [comment]
Didn't notice that (using Android 10 w/ Dark mode), sorry for any trouble added :)

**Comment by MBach** [comment]
It's not your MR, but I also update dependencies to keep the App up to date. If I don't find a solution quickly I'll fix the dependencies for a while and publish a minor release for F-Droid.
