### ISSUE TITLE
No way to connect to LeMonde account

### ISSUE THREAD

**Issue by mossssp** [MBach/LeMondeRssReader#38]
Hi,

Thank you for developing LeMondeRssReader.

I have just subscribe to LeMonde and I have not found how to connect to my account.

In my application, I have not the following red square features :
![image](https://user-images.githubusercontent.com/72909238/111275595-9a4c9c00-8636-11eb-8f50-7383aa444b59.png)

I am using the last version available in F-Droid : 2.1.4.
My Android version is 8.0.0.

Am I missing something ?

**Comment by mossssp** [comment]
This is also missing : 
![image](https://user-images.githubusercontent.com/72909238/111276276-763d8a80-8637-11eb-9fa4-791ac3364e9e.png)

**Comment by MBach** [comment]
Screenshots are outdated. I've not succeeded to make login to Lemonde.fr, due to securities reasons and lack of time to investigate. Therefore, I've removed this feature.

**Comment by MBach** [comment]
Done with https://github.com/MBach/LeMondeRssReader/releases/tag/v4.0.2 @mossssp
