### ISSUE TITLE
Privacy leak in LeMondeRssReader ?

### ISSUE THREAD

**Issue by iiitomo** [MBach/LeMondeRssReader#39]
Thanks a lot for this nice app.
I'm surprised to discover that LeMondeRssReader repeatedly connects to 
dualstack.osff2.map.fastly 
and s2.shared.global.fastly.net
, and this is reported /blocked as a privacy leak by TrackerControl.

Please can you remove these connections, or explain why they are necessary?

**Comment by MBach** [comment]
Hi @iiitomo,
I have no freaking idea of what your talking about!
This App is just a parser of the RSS fead, nothing more. You can search for `dualstack` or `fastly` in this repository, you will not find anything relevant.
Regards,

**Comment by kasnder** [comment]
I'm the developer of TrackerControl. `fastly.net` is probably used by an RSS feed that is contacted through this app. It is a content delivery network, and is probably not of much concern.
