### ISSUE TITLE
Don't use alpha/beta/rc versions of the android gradle plugin for releases

### ISSUE THREAD

**Issue by Bubu** [MBach/LeMondeRssReader#4]
Unfortunately google never publishes any source code for non-release versions of the android gradle plugin. F-Droid needs to be able to build the app with only free software, so we can't use such pre-release versions.

Could you stick to release versions of the plugin for your releases?

We'll replace this in a prebuild step for v1.8, see: https://gitlab.com/fdroid/fdroiddata/merge_requests/3138

**Comment by MBach** [comment]
@Bubu Plugin 3.1.2 should be OK!
