### ISSUE TITLE
live content 

### ISSUE THREAD

**Issue by smtgpm** [MBach/LeMondeRssReader#49]
Hi,

I've looked in the closed and opened issues and have not seen any request for this which surprises me, but any chance we could also get access to the content of the "live" sections ? Usually very interesting content ...

Thanks

**Comment by MBach** [comment]
Hi @smtgpm ,
I'm currently reworking on this App recently. It's going to be fully rewritten in Typescript, with Live section too. LeMonde changed the live feed, like a living website, so, I need to adjust my code.

**Comment by smtgpm** [comment]
Nice update, thanks ! Live content is available on my end :)
