### ISSUE TITLE
live writes content 3 times

### ISSUE THREAD

**Issue by smtgpm** [MBach/LeMondeRssReader#53]
Somehow the content of each live section is written 3 times 
![Uploading Screenshot_2023-02-18-07-59-32-55_a30882fe719e86a70765f21cb9966e4f.jpg…]()

**Comment by smtgpm** [comment]
Adding a screenshot as original one doesn't seem properly uploaded
![Screenshot_2023-02-28-16-19-59-61_a30882fe719e86a70765f21cb9966e4f](https://user-images.githubusercontent.com/16578119/221982830-0af3c56d-7ead-416b-aa7f-87b54b4d7d25.jpg)

**Comment by MBach** [comment]
Done with latest release https://github.com/MBach/LeMondeRssReader/releases/tag/v3.0.2
