### ISSUE TITLE
La aille de police est trop trop petit

### ISSUE THREAD

**Issue by salutkun** [MBach/LeMondeRssReader#55]
La taille de police est trop trop petite :

![Screenshot_20230323_011950_LeMondeRssReader](https://user-images.githubusercontent.com/3318669/226987034-5921da06-47f8-4adb-a63b-274646d977af.jpg)

**Comment by MBach** [comment]
La taille de la police est dynamique et suit les préférences système :
![Screenshot_20230504-222953_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/236322475-d096604a-8a8a-452d-9ab3-3998678d46fa.png)
![Screenshot_20230504-223025_LeMondeRssReader](https://user-images.githubusercontent.com/1532657/236322482-b3547620-68e7-4b85-b0b0-f64341bc923a.png)

**Comment by MBach** [comment]
Je ne vais pas ajouter d'options dans les paramètres de l'App, mais je suis preneur de toute PR
