### ISSUE TITLE
Keep Screen On should be optional

### ISSUE THREAD

**Issue by ygoltrant** [MBach/LeMondeRssReader#62]
Hi,
First things first : thank you very much for your project!

I've just understood why my phone sometimes wasn't turning to sleep : #54 
For my part, I think it's a bad idea to keep screen on : when I read an article, I'm focusing on it, which means I'm regularly touching the screen (to read more, change of article, etc.) This way, my phone won't enter in sleep mode in the middle of the article. The only moment the 'keep screen on' feature works is thus when I'm not focusing on my phone… expecting it to go to sleep.

So I can understand why keeping the screen on can sometimes be a good idea, but I think it should be optional.
I'm also not sure it should be default as I really thought there was something off with my phone until recently…

What do you think of such an enhancement ? The "keep screen on" as an option, deactivated by default ?

Have a good day

**Comment by MBach** [comment]
Well, when I'm cooking or eating, I'm usually reading an article... so I like to have the screen on.
I'll move this feature as optional, but not deactivated by default ;-)

**Comment by ygoltrant** [comment]
Well, your choice! Thanks for adding the option anyway ;-)

**Comment by MBach** [comment]
Done with latest release https://github.com/MBach/LeMondeRssReader/releases/tag/v3.0.2
