### ISSUE TITLE
Some features needed 

### ISSUE THREAD

**Issue by onos1** [MBach/LeMondeRssReader#7]
- The whole article is in French, but can't be toggled in the settings, but the app features was written in English on F-droid. 

- Also there is a favorite folder where you can check your favorite articles, but you can't add any there as there seem to be no way to star an article just to share when opened

**Comment by MBach** [comment]
Hello @onos1 
Well, I'm scrapping content written in French, so it doesn't seem illogical to me to have everything in French, no?
About the favorite folder, you're right, this feature is not yet implemented.

**Comment by onos1** [comment]
please  why did you tag this issue as a `bug`

**Comment by MBach** [comment]
Closed with commit https://github.com/MBach/LeMondeRssReader/commit/00e4b6eb43eae60280d38e2229e7606ae1d15477
