### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by klauf** [MBach/LeMondeRssReader#9]
Hi all
Thanks for this great app. However, since the last update I get no content, the app shows no article, same for all categories. It seems it doesn't load correctly. Anyone also encounters this?
regards

**Comment by MBach** [comment]
Already fixed with latest commit and [1.10](https://github.com/MBach/LeMondeRssReader/releases/download/v1.10/LeMondeRssReader-1.10.apk) release. LeMonde.fr has switched to https recently.

**Comment by klauf** [comment]
Thanks. Indeed. F-Droid was maybe a few days late. Updated and working now.
